# Custom feed configurations
custom_feeds:
  # Example of a custom feed (commented out)
  mta_bus:
    url: "https://gtfsrt.prod.obanyc.com/vehiclePositions?key="
    api_token: ""  # Optional
    headers: {}  # Optional additional headers
